version: '3.7'

services:
  server:
    image: node:12
    container_name: server
    expose:
        - 80
    environment:
        - NODE_ENV=development
        - VIRTUAL_HOST=server.chat
        - VIRTUAL_PORT=80
        - APP_PORT=80
    volumes:
        - ../BackEnd:/app
    command: bash -c "yarn && yarn dev"
    working_dir: /app

  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/cors.conf:/etc/nginx/vhost.d/default_location
    ports:
      - 80:80
